#!/bin/bash

eval "$(docker-machine env default)"

DEPRECATED=()
PORT=7474

function electport() {
    awk="BEGIN { FS = \"( ){2,}\" } { if (\$2 == \"cheminotorg/dbtest\") print \$6 }"

    ports=($(docker ps | awk -- "$awk"))

    regex="[0-9]+.[0-9]+.[0-9]+.[0-9]+:[0-9]{4}->([0-9]{4})/tcp"

    for port in $ports;
    do
        if [[ $port =~ $regex ]]; then
            p=${BASH_REMATCH[1]}
            if [ "$p" -ge $PORT ] ; then
                PORT=$(($p + 1))
            fi
        fi
    done
}

function identifydeprecated() {
    awk="BEGIN { FS = \"( ){2,}\" } { if (\$2 == \"cheminotorg/dbtest\") print \$1 }"

    DEPRECATED=($(docker ps | awk -- "$awk"))
}

function shutdowndeprecated() {
    for id in $DEPRECATED;
    do
        echo "Shutting down $id"
        docker stop $id
    done
}

####################################################

electport

identifydeprecated

docker run  -d -p $PORT:$PORT cheminotorg/dbtest
echo "Listening on ${PORT}..."

sleep 1

shutdowndeprecated

docker ps | grep "cheminotorg/dbtest"
